project:
  type: website

website:
  title: "Celin's ISSS608 Site"
  favicon: "Assets/orange_cat_favicon.ico"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exercise 3 Part 1"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
        - text: "Hands-on Exercise 3 Part 2"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03_Part2.html"
        - text: "Hands-on Exercise 4 Part 1"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_Part1.html"
        - text: "Hands-on Exercise 4 Part 2"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_Part2.html"
        - text: "Hands-on Exercise 4 Part 3"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_Part3.html"
        - text: "Hands-on Exercise 4 Part 4"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_Part4.html"
        - text: "Hands-on Exercise 5"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
        - text: "Hands-on Exercise 6"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
        - text: "Hands-on Exercise 7"
          href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"
        - text: "Hands-on Exercise 8 Part 1"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html"
        - text: "Hands-on Exercise 8 Part 2"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08_Part2.html"
        - text: "Hands-on Exercise 8 Part 3"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08_Part3.html"
        - text: "Hands-on Exercise 9 Part 1"
          href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.html"
        - text: "Hands-on Exercise 10"
          href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html"
    - text: "In-Class Exercise"
      menu:
        - text: "In-Class Exercise 1"
          href: "In-Class%20_Ex/In-Class_Ex01/In-Class_Ex01.html"
        - text: "In-Class Exercise 2"
          href: "In-Class%20_Ex/In-Class_Ex02/In-Class_Ex02.html"
        - text: "In-Class Exercise 3"
          href: "In-Class%20_Ex/In-Class_Ex03/In-Class_Ex03.html"
        - text: "In-Class Exercise 4"
          href: "In-Class%20_Ex/In-Class_Ex04/In-Class_Ex04.html"
        - text: "In-Class Exercise 5"
          href: "In-Class%20_Ex/In-Class_Ex05/In-Class_Ex05.html"
        - text: "In-Class Exercise 6"
          href: "In-Class%20_Ex/In-Class_Ex06/In-Class_Ex06.html"
        - text: "In-Class Exercise 7"
          href: "In-Class%20_Ex/In-Class_Ex07/In-Class_Ex07.html"
        - text: "In-Class Exercise 8"
          href: "In-Class%20_Ex/In-Class_Ex08/In-Class_Ex08.html"
        - text: "In-Class Exercise 9"
          href: "In-Class%20_Ex/In-Class_Ex09/In-Class_Ex09.html"
        - text: "In-Class Exercise 10"
          href: "In-Class%20_Ex/In-Class_Ex10/In-Class_Ex10.html"
    - text: "Take-Home Exercise"
      menu:
        - text: "Take-Home Exercise 1 Part 1"
          href: "Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01.html"
        - text: "Take-Home Exercise 1 Part 2"
          href: "Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01_Part2.html"
        - text: "Take-Home Exercise 2"
          href: "Take-Home_Ex/Take-Home_Ex02/Take-Home_Ex02.html"
          
          
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: visual

